# Generated by Django 2.2 on 2020-11-19 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('fe28ce60-0e4c-4f80-8cba-2d5eeff2813d')),
        ),
    ]
