# Generated by Django 2.2 on 2020-10-06 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('679288ea-6bc6-4135-9637-660e10bcbb7a')),
        ),
    ]
