# Generated by Django 2.2 on 2020-10-08 05:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201008_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('4349fc4d-837a-4991-9913-b44e89ba94a2')),
        ),
    ]
