# Generated by Django 2.2 on 2021-03-05 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210301_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='message',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='withdraw_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('bd387f3d-adb3-4d38-a318-4b011089431b')),
        ),
    ]
