# Generated by Django 2.2 on 2021-04-06 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210404_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_currency',
            field=models.CharField(blank=True, choices=[('Dollars', 'Dollars'), ('Pounds', 'Pounds'), ('Euros', 'Euros')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('47601f71-e54a-4101-9a39-ff0fe4682774')),
        ),
    ]
